# 端口配置
server:
  port: 8080

spring:
  # 配置数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/qbook?serverTimezone=UTC&characterEncoding=utf-8
    data-username: root
    data-password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #druid 数据源专有配置
    initialSize: 5   #初始化时建立物理连接的个数
    minIdle: 5    #最小连接池数量
    maxActive: 20   #最大连接池数量
    maxWait: 60000    #获取连接时最大等待时间
    timeBetweenEvictionRunsMillis: 60000    #Destory线程检测连接的间隔时间
    minEvictableIdleTimeMillis: 300000    #连接保持空闲而不被驱逐的最长时间
    validationQuery: SELECT 1 FROM DUAL    #检测连接是否有效的sql
    testWhileIdle: true
    testOnBorrow: false   #申请连接时执行validationQuery检测连接是否有效
    testOnReturn: false    #归还连接时执行validationQuery检测连接是否有效
    poolPreparedStatements: true   #是否缓存preparedStatements
    #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
    #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
    #则导入 log4j 依赖即可
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

logging:
  config: log4j2.config.xml
  level:
    cn.jay.repository: trace